simenv: add runtest command

diff --git a/simenv b/simenv
--- a/simenv
+++ b/simenv
@@ -1,7 +1,6 @@
 #!/bin/sh
 
 die() {
-	local p=$1 ; shift ;
 	echo "$@" >&2 ; exit 1 ;
 }
 
@@ -13,7 +12,7 @@ cpto() {
 		*) die "usage: cpto DEST" ;;
 	esac
 	read -r from
-	test -f "$from" || die cpto "cpto: invalid source file read from stdin"
+	test -f "$from" || die "cpto: invalid source file read from stdin"
 	cp "$from" "$to" && echo "$to"
 }
 
@@ -35,37 +34,118 @@ stime() {
 }
 
 vircheck() {
-	comment "vircheck FILE.vhdl - Cnvert FILE.vhdl to FILE.vir and view it"
-	f=`mktemp`
+	comment "vircheck FILE.vhdl : Cnvert FILE.vhdl to FILE.vir and view it"
+	local f=`mktemp`
 	runtr "$@" | xargs_ dist/build/VirCheck/VirCheck > $f
 	vim -c "set ft=haskell" `ospath $f`
 }
 
-runsim() {
-	comment "runsim FILE.vhdl - Generate Haskell code for FILE.vhdl"
+gensim() {
+	comment "gensim FILE.vhdl : Generate Haskell code for FILE.vhdl"
 	runtr "$@" | xargs_ dist/build/VSim/VSim | tee src_r/Test/Autogen.hs
 }
 
+
+runtest() { (
+	comment "runtest [-o LOGDIR] vhdl/FILE.vhd : Compile and run the test. Return the path to the LOGDIR"
+	local tn=""
+	local out=""
+	while test -n "$1" ; do
+		case "$1" in
+			-o) out="$2"; shift;;
+			*) tn="$1" ;;
+		esac
+		shift
+	done
+
+	if test -z "$out" ; then
+		out=`mktemp -d`
+	fi
+
+	(
+	if test -z "$tn" ; then
+		die "TEST_NAME argument is required"
+	fi
+
+	VSIM=dist/build/VSim/VSim
+	test -x "$VSIM" ||
+		die "$VSIM is not an executable"
+	
+	TST=src_r/Test/`basename $tn .vhd`
+	if test -f "$TST" ; then
+		rm -rf "$TST" ||
+			die "error: File $TST exists and I can't delete it"
+	fi
+
+	if test -f "$TST.hs" ; then
+		rm -rf "$TST.hs" ||
+			die "error: File $TST.hs exists and I can't delete it"
+	fi
+
+	date > $out/date
+	( runtr "$tn" ; echo $? >&2 ; ) 2> $out/transl.log |
+	( read -r x ; 
+	  cat $x > $out/transl.vir ;
+	  dist/build/VSim/VSim $x ;
+	  echo $? >&2 ;
+	) 2> $out/vsim.log |
+	tee $TST.hs > $out/sim.hs
+
+	GHC_SRC=`ospath $TST.hs`
+	GHC_OUT=`ospath $TST`
+
+	( stime -o $out/ghc.time \
+		ghc --make -O2 -isrc_r "$GHC_SRC" -o $GHC_OUT 2>&1 ; echo $? ; ) | tee $out/ghc.log
+	if ! test -x "$TST" ; then
+		die "$TST is not an executable"
+	fi
+
+	( stime -o $out/binary.time $TST ; echo $? ; ) | tee $out/binary.log
+
+	) 2>&1 | tee $out/script.log >&2
+
+	echo $out
+) }
+
+catall() {
+	while read d ; do
+		(
+		echo 
+		echo "listing $d"
+		echo "==========================="
+		echo 
+
+		cd $d || die "can't cd to $d"
+		for f in `ls -1` ; do
+			case $f in
+				*log|*.hs|*.vir) echo "$f:" ; cat -n $f ;;
+				*) echo non-log: "$f" ;;
+			esac
+		done
+		)
+	done
+}
+
 viewtr() {
-	comment "runsim FILE.vhdl - Generate FILE.vir and view it"
+	comment "viewtr FILE.vhdl : Generate FILE.vir and view it"
 	local f=`runtr "$@"`&& vim $f -c "set ft=lisp"
 }
 
 runaldec() { (
-	comment "runaldec FILE.vhd - Run the aldec simulator"
+	comment "runaldec FILE.vhd : Run the aldec simulator"
 
 	CWD=`pwd`
 	case $1 in
 		/*vhd|/*vhdl) VHD=$1 ;;
 		*vhd|*vhdl) VHD=$PWD/$1 ;;
-		*) die runtr "usage: runtr VHDL_FILE" ;;
+		*) die "usage: runtr VHDL_FILE" ;;
 	esac
 
 	WORK=.aldec
 	rm -rf $WORK >/dev/null 2>&1
 	mkdir $WORK >/dev/null 2>&1
 	cd $WORK ||
-		die runaldec "can't cd into $WORK"
+		die "can't cd into $WORK"
 
 	ENTITY=`sed -n 's@entity \(.*\) is@\1@ p' $VHD | head -n 1`
 	echo "Using entity name $ENTITY" >&2
@@ -84,29 +164,29 @@ runaldec() { (
 	) > './a.do'
 
 	stime vsimsa '-do' 'a.do' ||
-		die runaldec "Aldec reported error $?"
+		die "Aldec reported error $?"
 ) }
 
 aldecwave() {
-	comment "aldecwave  - view Aldec waveforms"
+	comment "aldecwave : view Aldec waveforms generated by the last call to runaldec"
 	avhdl.exe .aldec/wave.asdb
 }
 
 
 runghdl() { (
-	comment "runghdl FILE.vhdl - Run ghdl simulator"
+	comment "runghdl FILE.vhdl : Run ghdl simulator"
 	CWD=`pwd`
 	case $1 in
 		/*vhd|/*vhdl) VHD=$1 ;;
 		*vhd|*vhdl) VHD=$PWD/$1 ;;
-		*) die runghdl "usage: runtr VHDL_FILE" ;;
+		*) die "usage: runtr VHDL_FILE" ;;
 	esac
 
 	WORK=.ghdl
 	rm -rf $WORK >/dev/null 2>&1
 	mkdir $WORK >/dev/null 2>&1
 	cd $WORK ||
-		die runghdl "can't cd into $WORK"
+		die "can't cd into $WORK"
 
 	cp $VHD file.vhd
 
@@ -118,12 +198,12 @@ runghdl() { (
 ) }
 
 runtr() { (
-	comment "runtr FILE.vhdl - run java translator"
+	comment "runtr FILE.vhdl : run java translator"
 	CWD=`pwd`
 	case $1 in
 		/*vhd|/*vhdl) VHD=$1 ;;
 		*vhd|*vhdl) VHD=$PWD/$1 ;;
-		*) die runtr "usage: runtr VHDL_FILE" ;;
+		*) die "usage: runtr VHDL_FILE" ;;
 	esac
 
 	JAVABIN=$CWD/tr/bin
@@ -134,7 +214,7 @@ runtr() { (
 	rm -rf $WORK >/dev/null 2>&1
 	mkdir $WORK >/dev/null 2>&1
 	cd $WORK ||
-		die runtr "can't cd into $WORK"
+		die "can't cd into $WORK"
 
 	(
 	echo STD
@@ -167,7 +247,7 @@ runtr() { (
 		`ospath $VHD` \
 		work.$ENTITY \
 		`ospath $VIRFILE` >&2 ||
-			die runtr "translator failed"
+			die "translator failed"
 
 	echo `ospath $VIRFILE`
 ) }
@@ -192,14 +272,14 @@ countlines() {
 }
 
 linesofcode() {
-	comment "linesofcode - Count the size of a project in lines of code"
+	comment "linesofcode : Count the size of a project in lines of code"
 	printf "runtime %s lines\n" `countlines src_r`
 	printf "all     %s lines\n" `countlines .`
 }
 
 help() {
 	declare -f | grep -v grep | sed -n 's@.*comment.*"\(.*\)".*@\1@g p' |
-		awk -F '-' '{ printf("%-20s - %s\n",$1,$2);}'
+		awk -F ':' '{ printf("%-20s - %s\n",$1,$2);}'
 }
 
 if ! echo $0 | grep -q sh ; then (
